import { ProductGridSection } from "@/components/product-grid-section" // Updated import path

export function TrendingProducts() {
  const products = [
    {
      name: "IQOO Z7S 5G (6/128) GB, MISTY...",
      discount: "30%",
      price: "₹ 13999",
      oldPrice: "₹ 19999",
      quantityLeft: 10,
      quality: "Mint",
      imageSrc: "/iqooz7.png",
      linkHref: `/products/iqoo/iqoo-z7s-5g-misty`,
    },
    {
      name: "REALME NARZO 60X 5G (6/128) GB, NEBULA...",
      discount: "25%",
      price: "₹ 12999",
      oldPrice: "₹ 17000",
      quantityLeft: 8,
      quality: "Excellent",
      imageSrc: "/narxo60x.png",
      linkHref: `/products/realme/realme-narzo-60x-5g`,
    },
    {
      name: "MOTO G52 5G (6/128) GB, OLIVE...",
      discount: "20%",
      price: "₹ 13499",
      oldPrice: "₹ 17000",
      quantityLeft: 5,
      quality: "Good",
      imageSrc: "/motog52.png",
      linkHref: `/products/moto/moto-g52-5g`,
    },
    {
      name: "SAMSUNG 45W POWER ADAPTER...",
      discount: "15%",
      price: "₹ 1999",
      oldPrice: "₹ 2350",
      quantityLeft: 20,
      quality: "New",
      imageSrc: "/smsungpoweradptor.png",
      linkHref: `/products/samsung/samsung-45w-adapter`,
    },
    {
      name: "IQOO Z7S 5G (6/128) GB, PACIFIC NIGHT",
      discount: "30%",
      price: "₹ 13999",
      oldPrice: "₹ 19999",
      quantityLeft: 10,
      quality: "Mint",
      imageSrc: "/iqooz7.png",
      linkHref: `/products/iqoo/iqoo-z7s-5g-pacific-night`,
    },
    {
      name: "VIVO V30 5G (8/128) GB, PEACOCK...",
      discount: "28%",
      price: "₹ 28999",
      oldPrice: "₹ 40000",
      quantityLeft: 7,
      quality: "Excellent",
      imageSrc: "/V30.png",
      linkHref: `/products/vivo/vivo-v30-5g`,
    },
    {
      name: "SAMSUNG SUPER FAST CHARGING...",
      discount: "10%",
      price: "₹ 1099",
      oldPrice: "₹ 1200",
      quantityLeft: 15,
      quality: "New",
      imageSrc: "/charger.png",
      linkHref: `/products/samsung/samsung-super-fast-charging`,
    },
    {
      name: "SAMSUNG GALAXY S23 FE 5G (8/128) GB, CREAM",
      discount: "20%",
      price: "₹ 44999",
      oldPrice: "₹ 56000",
      quantityLeft: 3,
      quality: "Mint",
      imageSrc: "/s23FE.png",
      linkHref: `/products/samsung/samsung-galaxy-s23-fe-5g`,
    },
    {
      name: "VIVO V29E 5G (8/256) GB, RED...",
      discount: "22%",
      price: "₹ 23999",
      oldPrice: "₹ 30000",
      quantityLeft: 6,
      quality: "Excellent",
      imageSrc: "/v29e.png",
      linkHref: `/products/vivo/vivo-v29e-5g`,
    },
  ]

  return <ProductGridSection title="Trending Product" products={products} viewMoreLink="#" />
}
